// File: lib/firebase_options.dart
// This file is generated by FlutterFire CLI.
// To update it, run `flutterfire configure`

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI command `flutterfire configure`',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI command `flutterfire configure`',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAboT0Rpj06bFdbEgx-larykR0xeDXLDYU',
    appId: '1:240243879202:web:8d4c94c7462b65dfe0c97b',
    messagingSenderId: "240243879202",
    projectId: 'student-11edf',
    authDomain: 'student-11edf.firebaseapp.com',
    storageBucket: 'student-11edf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAboT0Rpj06bFdbEgx-larykR0xeDXLDYU',
    appId: '1:240243879202:android:d03761339f028b70e0c97b',
    messagingSenderId: '240243879202',
    projectId: 'student-11edf',
    storageBucket: 'student-11edf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAboT0Rpj06bFdbEgx-larykR0xeDXLDYU',
    appId: '1:240243879202:ios:5ce820bfc107ab31e0c97b',
    messagingSenderId: '240243879202',
    projectId: 'student-11edf',
    storageBucket: 'student-11edf.firebasestorage.app',
    iosClientId: '1.........-p............m.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentPortal',
  );
}