name: telegram
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  provider: ^6.1.5+1
  cloud_firestore: ^6.0.1
  fluttertoast: ^8.2.12
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  image_picker: ^1.2.0
  firebase_storage: ^13.0.1
  google_sign_in: ^7.1.1
  google_fonts: ^6.3.1
  swipe_cards: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/facebook-messenger-logo.png



